services:
  pg_test:
    image: postgres:16
    container_name: postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_test: {}